trigger:
  - develop

pool:
  vmImage: windows-latest

steps:
  - script: echo Starting CI pipeline!

  - task: UseDotNet@2
    displayName: "Install .NET SDK from global.json"
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: "restore"

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Build"
    inputs:
      command: "build"
